apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-role
rules:
- apiGroups: [""]
  resources:
  - pods
  - services
  - configmaps
  - secrets
  verbs: ["get", "watch", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-role-binding
subjects:
- kind: ServiceAccount
  name: grafana
roleRef:
  kind: Role
  name: grafana-role
  apiGroup: rbac.authorization.k8s.io
---  

